# Site settings
title: MrMadHatt's Blog
description: >-
  A personal tech journal and general blog with coding notes, project updates, and reflectionsâ€”written to connect with like-minded people along the way.
baseurl: "/blog" 
url: "https://MrMadHatt.github.io"

# Social Links
github_username: MrMadHatt
twitch_username: mr_madhat
linkedin_username: dominiq barbero
portfolio_url: https://mrmadhatt.github.io/my-portfolio/

# Build settings
theme: jekyll-theme-hacker
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/