# Site settings
title: MrMadHatt's Blog
description: >-
  Welcome to my blog where I share my thoughts, projects, and learnings. This is a space for me to connect with like-minded people and share my journey in the world of tech, programming, and more. Feel free to explore and join the conversation!
baseurl: "/blog" 
url: "https://MrMadHatt.github.io"

# Social Links
github_username: MrMadHatt
twitch_username: mr_madhat
linkedin_username: dominiq barbero
portfolio_url: https://mrmadhatt.github.io/my-portfolio/

# Build settings
theme: jekyll-theme-hacker
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/